"""Add scale_factor to MealPlanEntry

Revision ID: 52f824675e41
Revises: 45cfe913da79
Create Date: 2026-05-18 15:59:38.790562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52f824675e41'
down_revision = '45cfe913da79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan_entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scale_factor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal_plan_entry', schema=None) as batch_op:
        batch_op.drop_column('scale_factor')

    # ### end Alembic commands ###
