"""rename ingredients to ingredients_text

Revision ID: f8f2af88bbdf
Revises:
Create Date: 2026-05-15 09:19:45.550675

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f8f2af88bbdf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.alter_column("ingredients", new_column_name="ingredients_text")


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recipe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ingredients", sa.TEXT(), nullable=True))
        batch_op.drop_column("ingredients_text")

    # ### end Alembic commands ###
